### ISSUE TITLE
[1.4] Agent fails to connect with empty Docker labels

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#2641]
Introduced in #2590 

```
I, [2017-07-28T11:15:52.044136 #1]  INFO -- Kontena::WebsocketClient: connecting to master at ws://207.154.247.4
E, [2017-07-28T11:15:52.045711 #1] ERROR -- Kontena::WebsocketClient: undefined method `join' for nil:NilClass
Did you mean?  JSON (NoMethodError)
/app/lib/kontena/websocket_client.rb:91:in `connect'
/app/lib/kontena/websocket_client.rb:80:in `block in start'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
```

Looks like `Docker.info['labels']` is `nil` if empty, the Docker API returns `{ ...., "Labels":null, ... }`.
