### ISSUE TITLE
CLI plugin loading is broken with DEBUG=plugins

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#3149]
Looks like the [`Kontena::PluginManager::Loader#report_tracking`](https://github.com/kontena/kontena/blob/fea8711fffae58d7d0d27576888335e4df7ec7ff/cli/lib/kontena/plugin_manager/loader.rb#L86) was broken in #2434 refactoring?

```
/kontena/test # DEBUG=plugin kontena plugin list
DEBUG Kontena CLI 1.4.0.dev (ruby-2.3.6+x86_64-linux-musl)
DEBUG Activating plugin kontena-plugin-cloud
DEBUG Loading plugin kontena-plugin-cloud from /root/.kontena/gems/2.3.6/gems/kontena-plugin-cloud-1.2.0/lib/kontena_cli_plugin.rb
DEBUG Loaded plugin kontena-plugin-cloud
 [error] Failed to load plugin: kontena-plugin-cloud from /root/.kontena/gems/2.3.6/gems/kontena-plugin-cloud-1.2.0
	Rerun the command with environment DEBUG=true set to get the full exception.
ERROR undefined local variable or method `spec' for #<Kontena::PluginManager::Loader:0x000055a0fce3cf68>
Did you mean?  inspect (NameError)
/kontena/cli/lib/kontena/plugin_manager/loader.rb:86:in `block in report_tracking'
/usr/lib/ruby/2.3.0/logger.rb:427:in `add'
/usr/lib/ruby/2.3.0/logger.rb:455:in `debug'
/kontena/cli/lib/kontena/plugin_manager/loader.rb:86:in `report_tracking'
/kontena/cli/lib/kontena/plugin_manager/loader.rb:43:in `load_plugin'
/kontena/cli/lib/kontena/plugin_manager/loader.rb:21:in `block in load_plugins'
/kontena/cli/lib/kontena/plugin_manager/loader.rb:17:in `each'
/kontena/cli/lib/kontena/plugin_manager/loader.rb:17:in `load_plugins'
/kontena/cli/lib/kontena/plugin_manager.rb:22:in `plugins'
/kontena/cli/lib/kontena/plugin_manager.rb:15:in `init'
/usr/local/bin/kontena:18:in `<main>'
DEBUG Running Kontena::MainCommand with ["plugin", "list"] -- callback matcher = 'nil'
DEBUG Running Kontena::Cli::PluginCommand with ["list"] -- callback matcher = 'nil'
DEBUG Running Kontena::Cli::Plugins::ListCommand with [] -- callback matcher = 'plugins list'
NAME    VERSION   DESCRIPTION
cloud   1.2.0     Kontena Cloud management for Kontena CLI (broken)
```
