### PR TITLE
Remove orphaned certificates and fix crashing migration

### LINKED ISSUE #3311: After upgrade to 1.5.0 master crashes during certificate re-encryption
After installing 1.5.0 master kept in migration loop, crashes during reencrypting of certificates:

```
kontena-master | Re-encrypting Certificate cassoviaexpres/dwalin.adaptiware.com...
kontena-master | undefined method `name' for nil:NilClass
kontena-master | undefined method `name' for nil:NilClass
kontena-master | /app/app/models/certificate.rb:22:in `to_path'
kontena-master | /app/db/migrations/31_reencrypt_vault_secrets.rb:12:in `block in up'
kontena-master | /usr/lib/ruby/gems/2.4.0/gems/mongoid-5.2.1/lib/mongoid/contextual/mongo.rb:678:in `yield_document'
kontena-master | /usr/lib/ruby/gems/2.4.0/gems/mongoid-5.2.1/lib/mongoid/contextual/mongo.rb:130:in `block in each'
kontena-master | /usr/lib/ruby/gems/2.4.0/gems/mongo-2.4.3/lib/mongo/collection/view/iterable.rb:45:in `block in each'
kontena-master | /usr/lib/ruby/gems/2.4.0/gems/mongo-2.4.3/lib/mongo/cursor.rb:111:in `block in each'
kontena-master | /usr/lib/ruby/gems/2.4.0/gems/mongo-2.4.3/lib/mongo/cursor.rb:111:in `each'
kontena-master | /usr/lib/ruby/gems/2.4.0/gems/mongo-2.4.3/lib/mongo/cursor.rb:111:in `each'
kontena-master | /usr/lib/ruby/gems/2.4.0/gems/mongo-2.4.3/lib/mongo/collection/view/iterable.rb:44:in `each'
kontena-master | /usr/lib/ruby/gems/2.4.0/gems/mongoid-5.2.1/lib/mongoid/query_cache.rb:221:in `each'
kontena-master | /usr/lib/ruby/gems/2.4.0/gems/mongoid-5.2.1/lib/mongoid/contextual/mongo.rb:129:in `each'
kontena-master | /usr/lib/ruby/gems/2.4.0/gems/mongoid-5.2.1/lib/mongoid/contextual.rb:20:in `each'
kontena-master | /usr/lib/ruby/gems/2.4.0/gems/mongoid-5.2.1/lib/mongoid/findable.rb:15:in `each'
kontena-master | /app/db/migrations/31_reencrypt_vault_secrets.rb:11:in `up'
kontena-master | /app/app/services/mongodb/migration.rb:6:in `migrate'
kontena-master | /app/app/services/mongodb/migration_proxy.rb:4:in `migrate'
kontena-master | /app/app/services/mongodb/migrator.rb:90:in `block in migrate_without_lock'
kontena-master | /app/app/services/mongodb/migrator.rb:87:in `each'
kontena-master | /app/app/services/mongodb/migrator.rb:87:in `migrate_without_lock'
kontena-master | /app/app/services/mongodb/migrator.rb:75:in `migrate'
kontena-master | config/puma.rb:11:in `block in _load_from'
kontena-master | /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/configuration.rb:271:in `block in run_hooks'
kontena-master | /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/configuration.rb:271:in `each'
kontena-master | /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/configuration.rb:271:in `run_hooks'
kontena-master | /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/cluster.rb:259:in `worker'
kontena-master | /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/cluster.rb:126:in `block (2 levels) in spawn_workers'
kontena-master | /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/cluster.rb:126:in `fork'
kontena-master | /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/cluster.rb:126:in `block in spawn_workers'
kontena-master | /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/cluster.rb:122:in `times'
kontena-master | /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/cluster.rb:122:in `spawn_workers'
kontena-master | /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/cluster.rb:200:in `check_workers'
kontena-master | /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/cluster.rb:465:in `run'
kontena-master | /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/launcher.rb:174:in `run'
kontena-master | /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/cli.rb:77:in `run'
kontena-master | /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/bin/puma:10:in `<top (required)>'
kontena-master | /usr/bin/puma:23:in `load'
kontena-master | /usr/bin/puma:23:in `<main>'
kontena-master | [576] + Gemfile in context: /app/Gemfile
kontena-master | /app/app/services/mongodb/migration.rb:12:in `rescue in migrate': undefined method `name' for nil:NilClass (NoMethodError)
kontena-master |        from /app/app/services/mongodb/migration.rb:4:in `migrate'
kontena-master |        from /app/app/services/mongodb/migration_proxy.rb:4:in `migrate'
kontena-master |        from /app/app/services/mongodb/migrator.rb:90:in `block in migrate_without_lock'
kontena-master |        from /app/app/services/mongodb/migrator.rb:87:in `each'
kontena-master |        from /app/app/services/mongodb/migrator.rb:87:in `migrate_without_lock'
kontena-master |        from /app/app/services/mongodb/migrator.rb:75:in `migrate'
kontena-master |        from config/puma.rb:11:in `block in _load_from'
kontena-master |        from /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/configuration.rb:271:in `block in run_hooks'
kontena-master |        from /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/configuration.rb:271:in `each'
kontena-master |        from /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/configuration.rb:271:in `run_hooks'
kontena-master |        from /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/cluster.rb:259:in `worker'
kontena-master |        from /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/cluster.rb:126:in `block (2 levels) in spawn_workers'
kontena-master |        from /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/cluster.rb:126:in `fork'
kontena-master |        from /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/cluster.rb:126:in `block in spawn_workers'
kontena-master |        from /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/cluster.rb:122:in `times'
kontena-master |        from /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/cluster.rb:122:in `spawn_workers'
kontena-master |        from /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/cluster.rb:200:in `check_workers'
kontena-master |        from /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/cluster.rb:465:in `run'
kontena-master |        from /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/launcher.rb:174:in `run'
kontena-master |        from /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/cli.rb:77:in `run'
kontena-master |        from /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/bin/puma:10:in `<top (required)>'
kontena-master |        from /usr/bin/puma:23:in `load'
kontena-master |        from /usr/bin/puma:23:in `<main>'
```

### LINKED ISSUE #3312: Deleting a grid leaves behind orphan certificates
The `has_many :certificates` does not have the `dependent: :destroy` cascading rule.

The result is that upgrading to 1.5 goes into migration crash loop if you have deleted a grid that had certificates, as seen in #3311

### PR DESCRIPTION
**Pull request by kke**
Fixes #3311 
Fixes #3312 

Upgrading to 1.5.0 goes into a crash loop if you ever had a grid with certificates and deleted the grid.

The grid `has_many :certificates` did not have the `dependent: :destroy` option enabled, so any certificates were left behind after a grid was removed.

This PR fixes that by adding the option, skipping gridless certificates in the migration and adding a new migration to clean up any orphaned certificates from the database.

### CODE REVIEW

**Comment by SpComb** [comment]
Added a spec for the 31 migration

```
Failures:

  1) ReencryptVaultSecrets with certificates for a deleted grid does not crash
     Failure/Error: expect{described_class.up}.to_not raise_error
       expected no Exception, got #<NoMethodError: undefined method `name' for nil:NilClass> with backtrace:
         # ./app/models/certificate.rb:22:in `to_path'
         # ./db/migrations/31_reencrypt_vault_secrets.rb:12:in `block in up'
         # ./vendor/bundle/ruby/2.3.0/gems/mongoid-5.2.1/lib/mongoid/contextual/mongo.rb:678:in `yield_document'
         # ./vendor/bundle/ruby/2.3.0/gems/mongoid-5.2.1/lib/mongoid/contextual/mongo.rb:130:in `block in each'
         # ./vendor/bundle/ruby/2.3.0/gems/mongo-2.4.3/lib/mongo/collection/view/iterable.rb:45:in `block in each'
         # ./vendor/bundle/ruby/2.3.0/gems/mongo-2.4.3/lib/mongo/cursor.rb:111:in `block in each'
         # ./vendor/bundle/ruby/2.3.0/gems/mongo-2.4.3/lib/mongo/cursor.rb:111:in `each'
         # ./vendor/bundle/ruby/2.3.0/gems/mongo-2.4.3/lib/mongo/cursor.rb:111:in `each'
         # ./vendor/bundle/ruby/2.3.0/gems/mongo-2.4.3/lib/mongo/collection/view/iterable.rb:44:in `each'
         # ./vendor/bundle/ruby/2.3.0/gems/mongoid-5.2.1/lib/mongoid/query_cache.rb:221:in `each'
         # ./vendor/bundle/ruby/2.3.0/gems/mongoid-5.2.1/lib/mongoid/contextual/mongo.rb:129:in `each'
         # ./vendor/bundle/ruby/2.3.0/gems/mongoid-5.2.1/lib/mongoid/contextual.rb:20:in `each'
         # ./vendor/bundle/ruby/2.3.0/gems/mongoid-5.2.1/lib/mongoid/findable.rb:15:in `each'
         # ./db/migrations/31_reencrypt_vault_secrets.rb:11:in `up'
         # ./spec/db/migrations/31_rencrypt_vault_secrets_spec.rb:147:in `block (5 levels) in <top (required)>'
         # ./spec/db/migrations/31_rencrypt_vault_secrets_spec.rb:147:in `block (4 levels) in <top (required)>'
         # ./spec/spec_helper.rb:88:in `block (3 levels) in <top (required)>'
         # ./spec/spec_helper.rb:87:in `block (2 levels) in <top (required)>'
     # ./spec/db/migrations/31_rencrypt_vault_secrets_spec.rb:147:in `block (4 levels) in <top (required)>'
     # ./spec/spec_helper.rb:88:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:87:in `block (2 levels) in <top (required)>'

Finished in 1.19 seconds (files took 1.9 seconds to load)
22 examples, 1 failure

Failed examples:

rspec ./spec/db/migrations/31_rencrypt_vault_secrets_spec.rb:146 # ReencryptVaultSecrets with certificates for a deleted grid does not crash

```
