### ISSUE TITLE
After upgrade to 1.5.0 master crashes during certificate re-encryption

### ISSUE THREAD

**Issue by Edke** [kontena/kontena#3311]
After installing 1.5.0 master kept in migration loop, crashes during reencrypting of certificates:

```
kontena-master | Re-encrypting Certificate cassoviaexpres/dwalin.adaptiware.com...
kontena-master | undefined method `name' for nil:NilClass
kontena-master | undefined method `name' for nil:NilClass
kontena-master | /app/app/models/certificate.rb:22:in `to_path'
kontena-master | /app/db/migrations/31_reencrypt_vault_secrets.rb:12:in `block in up'
kontena-master | /usr/lib/ruby/gems/2.4.0/gems/mongoid-5.2.1/lib/mongoid/contextual/mongo.rb:678:in `yield_document'
kontena-master | /usr/lib/ruby/gems/2.4.0/gems/mongoid-5.2.1/lib/mongoid/contextual/mongo.rb:130:in `block in each'
kontena-master | /usr/lib/ruby/gems/2.4.0/gems/mongo-2.4.3/lib/mongo/collection/view/iterable.rb:45:in `block in each'
kontena-master | /usr/lib/ruby/gems/2.4.0/gems/mongo-2.4.3/lib/mongo/cursor.rb:111:in `block in each'
kontena-master | /usr/lib/ruby/gems/2.4.0/gems/mongo-2.4.3/lib/mongo/cursor.rb:111:in `each'
kontena-master | /usr/lib/ruby/gems/2.4.0/gems/mongo-2.4.3/lib/mongo/cursor.rb:111:in `each'
kontena-master | /usr/lib/ruby/gems/2.4.0/gems/mongo-2.4.3/lib/mongo/collection/view/iterable.rb:44:in `each'
kontena-master | /usr/lib/ruby/gems/2.4.0/gems/mongoid-5.2.1/lib/mongoid/query_cache.rb:221:in `each'
kontena-master | /usr/lib/ruby/gems/2.4.0/gems/mongoid-5.2.1/lib/mongoid/contextual/mongo.rb:129:in `each'
kontena-master | /usr/lib/ruby/gems/2.4.0/gems/mongoid-5.2.1/lib/mongoid/contextual.rb:20:in `each'
kontena-master | /usr/lib/ruby/gems/2.4.0/gems/mongoid-5.2.1/lib/mongoid/findable.rb:15:in `each'
kontena-master | /app/db/migrations/31_reencrypt_vault_secrets.rb:11:in `up'
kontena-master | /app/app/services/mongodb/migration.rb:6:in `migrate'
kontena-master | /app/app/services/mongodb/migration_proxy.rb:4:in `migrate'
kontena-master | /app/app/services/mongodb/migrator.rb:90:in `block in migrate_without_lock'
kontena-master | /app/app/services/mongodb/migrator.rb:87:in `each'
kontena-master | /app/app/services/mongodb/migrator.rb:87:in `migrate_without_lock'
kontena-master | /app/app/services/mongodb/migrator.rb:75:in `migrate'
kontena-master | config/puma.rb:11:in `block in _load_from'
kontena-master | /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/configuration.rb:271:in `block in run_hooks'
kontena-master | /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/configuration.rb:271:in `each'
kontena-master | /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/configuration.rb:271:in `run_hooks'
kontena-master | /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/cluster.rb:259:in `worker'
kontena-master | /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/cluster.rb:126:in `block (2 levels) in spawn_workers'
kontena-master | /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/cluster.rb:126:in `fork'
kontena-master | /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/cluster.rb:126:in `block in spawn_workers'
kontena-master | /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/cluster.rb:122:in `times'
kontena-master | /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/cluster.rb:122:in `spawn_workers'
kontena-master | /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/cluster.rb:200:in `check_workers'
kontena-master | /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/cluster.rb:465:in `run'
kontena-master | /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/launcher.rb:174:in `run'
kontena-master | /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/cli.rb:77:in `run'
kontena-master | /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/bin/puma:10:in `<top (required)>'
kontena-master | /usr/bin/puma:23:in `load'
kontena-master | /usr/bin/puma:23:in `<main>'
kontena-master | [576] + Gemfile in context: /app/Gemfile
kontena-master | /app/app/services/mongodb/migration.rb:12:in `rescue in migrate': undefined method `name' for nil:NilClass (NoMethodError)
kontena-master |        from /app/app/services/mongodb/migration.rb:4:in `migrate'
kontena-master |        from /app/app/services/mongodb/migration_proxy.rb:4:in `migrate'
kontena-master |        from /app/app/services/mongodb/migrator.rb:90:in `block in migrate_without_lock'
kontena-master |        from /app/app/services/mongodb/migrator.rb:87:in `each'
kontena-master |        from /app/app/services/mongodb/migrator.rb:87:in `migrate_without_lock'
kontena-master |        from /app/app/services/mongodb/migrator.rb:75:in `migrate'
kontena-master |        from config/puma.rb:11:in `block in _load_from'
kontena-master |        from /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/configuration.rb:271:in `block in run_hooks'
kontena-master |        from /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/configuration.rb:271:in `each'
kontena-master |        from /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/configuration.rb:271:in `run_hooks'
kontena-master |        from /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/cluster.rb:259:in `worker'
kontena-master |        from /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/cluster.rb:126:in `block (2 levels) in spawn_workers'
kontena-master |        from /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/cluster.rb:126:in `fork'
kontena-master |        from /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/cluster.rb:126:in `block in spawn_workers'
kontena-master |        from /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/cluster.rb:122:in `times'
kontena-master |        from /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/cluster.rb:122:in `spawn_workers'
kontena-master |        from /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/cluster.rb:200:in `check_workers'
kontena-master |        from /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/cluster.rb:465:in `run'
kontena-master |        from /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/launcher.rb:174:in `run'
kontena-master |        from /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/cli.rb:77:in `run'
kontena-master |        from /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/bin/puma:10:in `<top (required)>'
kontena-master |        from /usr/bin/puma:23:in `load'
kontena-master |        from /usr/bin/puma:23:in `<main>'
```

**Comment by kke** [comment]
That may indeed be true.

The `Grid` model does not have `dependent: delete` on the `has_many :certificates` relationship.

**Comment by kke** [comment]
As an emergency fix you could try to delete all certificates from mongo.

**Comment by kke** [comment]
Trying to release 1.5.1 with a fix ASAP

**Comment by Edke** [comment]
@kke thanks for super quick response, missed it as I was digging hard into Mongo :) I'm a Postgre person, so had to find way to do group by on certificates and then identify one that was as you described:
- part of grid
- I removed grid
- this certificate is orphan, it's "foreign_key" to grids collection is broken
- therefore exception

One thing to say here .. Mongo sucks :))))

Found orphan certificate, removed, then instantly migration process went though ..

But fixing this is a must, others may have similiar condition ..

**Comment by kke** [comment]
And anyone with a working < 1.5 installation should be able to avoid this by running:

```
$ kontena master ssh kontena-console
> Certificate.all.select { |c| c.grid.nil? }.map(&:destroy)
```

**Comment by Edke** [comment]
And I just found out that my way of backing up mongo before upgrade to mayor sucks ! So I was stuck with broken 1.5.0 db and had to figure out how to fix it.

**Comment by kke** [comment]
Yes the mongo shell query thing is super difficult to use compared to traditional SQL.
